CREATE TABLE stringed_instrument (
	id BIGINT NOT NULL,
	classification CHAR(50) NULL DEFAULT NULL,
	category CHAR(50) NULL DEFAULT NULL,
	name CHAR(50) NULL DEFAULT NULL,
	number_of_strings INT NULL DEFAULT NULL,
	PRIMARY KEY (id) USING BTREE
);