CREATE TABLE building_instrument (
	id BIGINT NOT NULL,
	instr_type CHAR(2) NULL DEFAULT NULL,
	classification CHAR(50) NULL DEFAULT NULL,
	name CHAR(50) NULL DEFAULT NULL,
	mass DOUBLE NULL DEFAULT NULL,
	power INTEGER NULL DEFAULT NULL,
	PRIMARY KEY (id) USING BTREE
);